apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    chart: my-app
    repoURL: https://github.com/selcuksan/helm-deployment-with-argocd/tree/main/kod-repo-A/helm-chart/my-app
    helm:
      releaseName: my-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default