apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-a
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://1.2.3.4
      - cluster: prod
        url: https://2.4.6.8
      - cluster: test
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-my-app-a'
    spec:
      project: my-app-a
      source:
        repoURL: https://github.com/selcuksan/helm-deployment-with-argocd.git
        targetRevision: HEAD
        path: kod-repo-A/helm-chart/my-app-1
      destination:
        server: '{{.url}}'
        namespace: app-set-demo